### ISSUE TITLE
Cannot build pkg Stream without user input

### ISSUE THREAD

**Issue by JesperBrink** [birgorg/bioconda_recipe_gen#157]
When building the pkg Stream our program finds the following error message `ModuleNotFoundError: No module named 'umap'` and therefore adds the pkg `umap` as an dependency.
However, what Stream needs is the pkg `umap-learn` which we have no change of knowing. The system will therefore not be able to build Stream.

But if the user corrects `umap` to `umap-learn` in the generated meta.yaml and runs our program again with that as input, it will successfully build.

**Comment by Hogfeldt** [comment]
Deprecated
