### ISSUE TITLE
Make scrappie pass sanity check

### ISSUE THREAD

**Issue by JesperBrink** [birgorg/bioconda_recipe_gen#86]

**Comment by JesperBrink** [comment]
I am having trouble finding the packages needed for this to build based on the error messages. The cause could be that this package as very different build.sh than our default, which needs to be run:
```
#!/bin/sh
 
 export C_INCLUDE_PATH=${PREFIX}/include
 export CPLUS_INCLUDE_PATH=${PREFIX}/include
 export LD_LIBRARY_PATH=${PREFIX}/lib
 export LIBRARY_PATH=${PREFIX}/lib
 
 mkdir build && cd build && \
 cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DBUILD_SHARED_LIB=ON ..
 make && make install
 
 cd ${SRC_DIR}/python
 $PYTHON setup.py install --single-version-externally-managed --record=record.txt
```

**Comment by JesperBrink** [comment]
After trying different things with the build.sh, I can conclude that we cannot find the `python` dependency without also having their build.sh which makes use of it.

**Comment by JesperBrink** [comment]
We choose not to look at this package for now, since it turns out to be very hard to build, even though we now have a dynamic build.sh. 

Problems: Could only find openblas and hdf5. After that no error message was found which could indicate the rest of the packages.

**Comment by Hogfeldt** [comment]
Deprecated
